interface DDDInfo {
  city: string;
  state: string;
  stateCode: string;
}

export const dddMapping: Record<string, DDDInfo> = {
  '11': { city: 'São Paulo', state: 'São Paulo', stateCode: 'SP' },
  '12': { city: 'São José dos Campos', state: 'São Paulo', stateCode: 'SP' },
  '13': { city: 'Santos', state: 'São Paulo', stateCode: 'SP' },
  '14': { city: 'Bauru', state: 'São Paulo', stateCode: 'SP' },
  '15': { city: 'Sorocaba', state: 'São Paulo', stateCode: 'SP' },
  '16': { city: 'Ribeirão Preto', state: 'São Paulo', stateCode: 'SP' },
  '17': { city: 'São José do Rio Preto', state: 'São Paulo', stateCode: 'SP' },
  '18': { city: 'Presidente Prudente', state: 'São Paulo', stateCode: 'SP' },
  '19': { city: 'Campinas', state: 'São Paulo', stateCode: 'SP' },
  '21': { city: 'Rio de Janeiro', state: 'Rio de Janeiro', stateCode: 'RJ' },
  '22': { city: 'Campos dos Goytacazes', state: 'Rio de Janeiro', stateCode: 'RJ' },
  '24': { city: 'Volta Redonda', state: 'Rio de Janeiro', stateCode: 'RJ' },
  '27': { city: 'Vitória', state: 'Espírito Santo', stateCode: 'ES' },
  '28': { city: 'Cachoeiro de Itapemirim', state: 'Espírito Santo', stateCode: 'ES' },
  '31': { city: 'Belo Horizonte', state: 'Minas Gerais', stateCode: 'MG' },
  '32': { city: 'Juiz de Fora', state: 'Minas Gerais', stateCode: 'MG' },
  '33': { city: 'Governador Valadares', state: 'Minas Gerais', stateCode: 'MG' },
  '34': { city: 'Uberlândia', state: 'Minas Gerais', stateCode: 'MG' },
  '35': { city: 'Poços de Caldas', state: 'Minas Gerais', stateCode: 'MG' },
  '37': { city: 'Divinópolis', state: 'Minas Gerais', stateCode: 'MG' },
  '38': { city: 'Montes Claros', state: 'Minas Gerais', stateCode: 'MG' },
  '41': { city: 'Curitiba', state: 'Paraná', stateCode: 'PR' },
  '42': { city: 'Ponta Grossa', state: 'Paraná', stateCode: 'PR' },
  '43': { city: 'Londrina', state: 'Paraná', stateCode: 'PR' },
  '44': { city: 'Maringá', state: 'Paraná', stateCode: 'PR' },
  '45': { city: 'Foz do Iguaçu', state: 'Paraná', stateCode: 'PR' },
  '46': { city: 'Francisco Beltrão', state: 'Paraná', stateCode: 'PR' },
  '47': { city: 'Joinville', state: 'Santa Catarina', stateCode: 'SC' },
  '48': { city: 'Florianópolis', state: 'Santa Catarina', stateCode: 'SC' },
  '49': { city: 'Chapecó', state: 'Santa Catarina', stateCode: 'SC' },
  '51': { city: 'Porto Alegre', state: 'Rio Grande do Sul', stateCode: 'RS' },
  '53': { city: 'Pelotas', state: 'Rio Grande do Sul', stateCode: 'RS' },
  '54': { city: 'Caxias do Sul', state: 'Rio Grande do Sul', stateCode: 'RS' },
  '55': { city: 'Santa Maria', state: 'Rio Grande do Sul', stateCode: 'RS' },
  '61': { city: 'Brasília', state: 'Distrito Federal', stateCode: 'DF' },
  '62': { city: 'Goiânia', state: 'Goiás', stateCode: 'GO' },
  '63': { city: 'Palmas', state: 'Tocantins', stateCode: 'TO' },
  '64': { city: 'Rio Verde', state: 'Goiás', stateCode: 'GO' },
  '65': { city: 'Cuiabá', state: 'Mato Grosso', stateCode: 'MT' },
  '66': { city: 'Rondonópolis', state: 'Mato Grosso', stateCode: 'MT' },
  '67': { city: 'Campo Grande', state: 'Mato Grosso do Sul', stateCode: 'MS' },
  '68': { city: 'Rio Branco', state: 'Acre', stateCode: 'AC' },
  '69': { city: 'Porto Velho', state: 'Rondônia', stateCode: 'RO' },
  '71': { city: 'Salvador', state: 'Bahia', stateCode: 'BA' },
  '73': { city: 'Ilhéus', state: 'Bahia', stateCode: 'BA' },
  '74': { city: 'Juazeiro', state: 'Bahia', stateCode: 'BA' },
  '75': { city: 'Feira de Santana', state: 'Bahia', stateCode: 'BA' },
  '77': { city: 'Barreiras', state: 'Bahia', stateCode: 'BA' },
  '79': { city: 'Aracaju', state: 'Sergipe', stateCode: 'SE' },
  '81': { city: 'Recife', state: 'Pernambuco', stateCode: 'PE' },
  '82': { city: 'Maceió', state: 'Alagoas', stateCode: 'AL' },
  '83': { city: 'João Pessoa', state: 'Paraíba', stateCode: 'PB' },
  '84': { city: 'Natal', state: 'Rio Grande do Norte', stateCode: 'RN' },
  '85': { city: 'Fortaleza', state: 'Ceará', stateCode: 'CE' },
  '86': { city: 'Teresina', state: 'Piauí', stateCode: 'PI' },
  '87': { city: 'Petrolina', state: 'Pernambuco', stateCode: 'PE' },
  '88': { city: 'Juazeiro do Norte', state: 'Ceará', stateCode: 'CE' },
  '89': { city: 'Picos', state: 'Piauí', stateCode: 'PI' },
  '91': { city: 'Belém', state: 'Pará', stateCode: 'PA' },
  '92': { city: 'Manaus', state: 'Amazonas', stateCode: 'AM' },
  '93': { city: 'Santarém', state: 'Pará', stateCode: 'PA' },
  '94': { city: 'Marabá', state: 'Pará', stateCode: 'PA' },
  '95': { city: 'Boa Vista', state: 'Roraima', stateCode: 'RR' },
  '96': { city: 'Macapá', state: 'Amapá', stateCode: 'AP' },
  '97': { city: 'Coari', state: 'Amazonas', stateCode: 'AM' },
  '98': { city: 'São Luís', state: 'Maranhão', stateCode: 'MA' },
  '99': { city: 'Imperatriz', state: 'Maranhão', stateCode: 'MA' },
};

export function getDDDInfo(ddd: string): DDDInfo {
  return dddMapping[ddd] || { 
    city: 'São Paulo', 
    state: 'São Paulo', 
    stateCode: 'SP' 
  };
}